version: '3.9'
services:

  nginx:
    image: 4kit0/yagodnaya-polyana-nginx:latest
    container_name: nginx
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nuxt
    volumes:
      - /etc/letsencrypt/live/yagodnaya-polyana.ru/:/etc/letsencrypt/live/yagodnaya-polyana.ru/
      - /etc/letsencrypt/:/etc/letsencrypt

  nuxt:
    image: 4kit0/yagodnaya-polyana:latest
    container_name: nuxt
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    restart: always
